Use existing Chrome with puppeteer
Seeing the following error, no matter what:

```
Running "qunit:all" (qunit) task
>> There was an error with headless chrome
Fatal error: Could not find Chrome (ver. 147.0.7727.57). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /home/runner/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Error: Process completed with exit code 1.
```

The referenced Chrome executable exists in the right place though, I can
only assume a problem with GitHub Actions runner, especially since we
didn't upgrade related packages in the past two weeks (when this all
worked fine).

We might be able to revert later.